### ISSUE TITLE
Leverage nsi-survey-tool css styling to have a consistent style

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#14]
in order to maintain a consistent user interface, we need to leverage consistent css for our toolset.

Right now this tool is using bootstrap and the sandstone bootswatch, but nsi survey tool is using a different solution. Lets move to the nsi-survey-tool css set.

**Comment by HenryGeorgist** [comment]
please use the rgoss branch for reference

**Comment by trietmnj** [comment]
Ok, the login page is the same for both the download and survey tools. However, do you really, really, really want to go with all black colorings for the main map page?

![image](https://user-images.githubusercontent.com/53122983/128540263-02560e07-71b0-4556-8f68-17e67a4f7396.png)

![image](https://user-images.githubusercontent.com/53122983/128539698-22372193-c2fd-4a30-8909-d29f5572d07d.png)

![image](https://user-images.githubusercontent.com/53122983/128539888-11d39dc0-aa49-480a-ab92-d0d288d90862.png)

**Comment by HenryGeorgist** [comment]
Sweet.
What do you think? One think I have considered is to have different color schemes for different sites, but keeping the same icon or things like that.

**Comment by trietmnj** [comment]
That's a good idea, it would be kind of like the MS Office Suite where there is a clear color association across the apps ie Excel-green, Word-blue, etc. If the location of the icons/functions do not change, then there shouldn't be an issue with the usability. Also, while developing, when I have both the download and the survey tool pulled up, having the same color theme makes it really confusing which tool I'm looking at sometimes. The user probably won't run into that issue though.

**Comment by HenryGeorgist** [comment]
@trietmnj propose a color scheme for the download tool the blue house stays the same color, so make it feel good with the blue house. I dont generally like white color schemes.

**Comment by trietmnj** [comment]
How about the coloring in the middle picture? Gray with a shade of dark blue for the darker tone (banner) and grayish beige for the highlight? The lighter tone goes really well with the map natural color.

![image](https://user-images.githubusercontent.com/53122983/128547058-ad964a61-f37c-47f1-86b9-f0f34e09429f.png)

**Comment by HenryGeorgist** [comment]
Can we make the popup the light gray color of the map  and loose the background and color on the state name.

**Comment by trietmnj** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/53122983/128565940-0326bef2-52fe-4b47-b900-882c1ac3692d.png)

**Comment by HenryGeorgist** [comment]
Yes! beautiful.

**Comment by HenryGeorgist** [comment]
make a pr and ask for review.
