### ISSUE TITLE
Uncaught TypeError: feature.getStyle is not a function

### ISSUE THREAD

**Issue by trietmnj** [HydrologicEngineeringCenter/nsi-ui#17]
TypeError: feature.getStyle is not a function
Select.applySelectedStyle_
/src/interaction/Select.js:410
  407 |  * @private
  408 |  */
  409 | Select.prototype.removeFeatureLayerAssociation_ = function (feature) {
> 410 |     delete this.featureLayerAssociation_[getUid(feature)];
      | ^  411 | };
  412 | /**
  413 |  * Handles the {@link module:ol/MapBrowserEvent map browser event} and may change the
View compiled
Select.addFeature_
/src/interaction/Select.js:381
  378 | Select.prototype.applySelectedStyle_ = function (feature) {
  379 |     var key = getUid(feature);
  380 |     if (!(key in originalFeatureStyles)) {
> 381 |         originalFeatureStyles[key] = feature.getStyle();
      | ^  382 |     }
  383 |     feature.setStyle(this.style_);
  384 | };
View compiled
Collection.Target.dispatchEvent
/src/events/Target.js:110
  107 |     dispatching[type] = 0;
  108 |     pendingRemovals[type] = 0;
  109 | }
> 110 | ++dispatching[type];
      | ^  111 | for (var i = 0, ii = listeners.length; i < ii; ++i) {
  112 |     if ('handleEvent' in listeners[i]) {
  113 |         propagate = /** @type {import("../events.js").ListenerObject} */ (listeners[i]).handleEvent(evt);
View compiled
Collection.insertAt
src/Collection.js:203
  200 |     this.array_.splice(index, 0, elem);
  201 |     this.updateLength_();
  202 |     this.dispatchEvent(new CollectionEvent(CollectionEventType.ADD, elem, index));
> 203 | };
      | ^  204 | /**
  205 |  * Remove the last element of the collection and return it.
  206 |  * Return `undefined` if the collection is empty.
View compiled
Collection.push
https://localhost:3000/static/js/vendors~main.chunk.js:201006:10
  201003 |   }
  201004 | 
  201005 |   var n = this.getLength();
> 201006 |   this.insertAt(n, elem);
         |        ^  201007 |   return this.getLength();
  201008 | };
  201009 | /**
View source
Collection.extend
src/Collection.js:140
  137 |  * to the end of the collection.
  138 |  * @param {!Array<T>} arr Array.
  139 |  * @return {Collection<T>} This collection.
> 140 |  * @api
      | ^  141 |  */
  142 | Collection.prototype.extend = function (arr) {
  143 |     for (var i = 0, ii = arr.length; i < ii; ++i) {
View compiled
Select.handleEvent
/src/interaction/Select.js:502
  499 |             this.dispatchEvent(new SelectEvent(SelectEventType.SELECT, selected, deselected, mapBrowserEvent));
  500 |         }
  501 |         return true;
> 502 |     };
  503 |     return Select;
  504 | }(Interaction));
  505 | /**
View compiled
▼ 3 stack frames were expanded.
Map.PluggableMap.handleMapBrowserEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:45810
MapBrowserEventHandler.Target.dispatchEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:6604
MapBrowserEventHandler.<anonymous>
node_modules/@corpsmap/corpsmap/lib/dev.js:42423
▲ 3 stack frames were expanded.

Replicable by fast clicking on different states.

**Comment by trietmnj** [comment]
TypeError: feature.setStyle is not a function
Select.restorePreviousStyle_
/src/interaction/Select.js:435
  432 | // Replace the currently selected feature(s) with the feature(s) at the
  433 | // pixel, or clear the selected feature(s) if there is no feature at
  434 | // the pixel.
> 435 | clear(this.featureLayerAssociation_);
      | ^  436 | map.forEachFeatureAtPixel(mapBrowserEvent.pixel, 
  437 | /**
  438 |  * @param {import("../Feature.js").FeatureLike} feature Feature.
View compiled
Select.removeFeature_
/src/interaction/Select.js:392
  389 | Select.prototype.restorePreviousStyle_ = function (feature) {
  390 |     var interactions = this.getMap().getInteractions().getArray();
  391 |     for (var i = interactions.length - 1; i >= 0; --i) {
> 392 |         var interaction = interactions[i];
      | ^  393 |         if (interaction !== this &&
  394 |             interaction instanceof Select &&
  395 |             interaction.getStyle() &&
View compiled
Collection.Target.dispatchEvent
/src/events/Target.js:110
  107 |     dispatching[type] = 0;
  108 |     pendingRemovals[type] = 0;
  109 | }
> 110 | ++dispatching[type];
      | ^  111 | for (var i = 0, ii = listeners.length; i < ii; ++i) {
  112 |     if ('handleEvent' in listeners[i]) {
  113 |         propagate = /** @type {import("../events.js").ListenerObject} */ (listeners[i]).handleEvent(evt);
View compiled
Collection.removeAt
src/Collection.js:260
  257 |  * Set the element at the provided index.
  258 |  * @param {number} index Index.
  259 |  * @param {T} elem Element.
> 260 |  * @api
      | ^  261 |  */
  262 | Collection.prototype.setAt = function (index, elem) {
  263 |     var n = this.getLength();
View compiled
Collection.remove
src/Collection.js:243
  240 |     return undefined;
  241 | };
  242 | /**
> 243 |  * Remove the element at the provided index and return it.
      | ^  244 |  * Return `undefined` if the collection does not contain this index.
  245 |  * @param {number} index Index.
  246 |  * @return {T|undefined} Value.
View compiled
Select.handleEvent
/src/interaction/Select.js:497
  494 |         features.remove(deselected[j]);
  495 |     }
  496 |     features.extend(selected);
> 497 | }
      | ^  498 | if (selected.length > 0 || deselected.length > 0) {
  499 |     this.dispatchEvent(new SelectEvent(SelectEventType.SELECT, selected, deselected, mapBrowserEvent));
  500 | }
View compiled
▼ 3 stack frames were expanded.
Map.PluggableMap.handleMapBrowserEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:45810
MapBrowserEventHandler.Target.dispatchEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:6604
MapBrowserEventHandler.<anonymous>
node_modules/@corpsmap/corpsmap/lib/dev.js:42423
▲ 3 stack frames were expanded.

Also this error. Both are thrown simultaneously

**Comment by HenryGeorgist** [comment]
i think this is in cm3 - i have seen it before. Is that right that it is in a cm3 js file?

**Comment by trietmnj** [comment]
The ultimate error is in ol. It's pointing to node_modules/ol/src/interaction/Select.js. The call did start from corpsmap though.

![image](https://user-images.githubusercontent.com/53122983/128579922-7859c134-ace7-49c7-9258-00f0947ef70e.png)

**Comment by trietmnj** [comment]
Could be from the async handling. I think the error has less chance of showing up when you click slower.

**Comment by HenryGeorgist** [comment]
oy. Ok. Do you have a path to resolution on the bug? We could do a double click selection action which would change the code path (from our current single click action for selecting and downloading a state?

**Comment by trietmnj** [comment]
I was thinking of introducing a time delay between each selection or see if there's a way to refresh just the map component on error, but the double click could work too.

**Comment by trietmnj** [comment]
I was wrong, the issue was witch clicking on the VTL points
