### ISSUE TITLE
add vtl endpoints for visualization of the NSI data

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#2]

**Comment by HenryGeorgist** [comment]
See this example. I think we would want to change the zoom level so that it loads earlier.

https://github.com/HydrologicEngineeringCenter/nsi-survey-tool/blob/master/src/cm-plugins/vtl/cm3-nsi-vtl-bundle.js

This won't work until we get the login page completed.

**Comment by HenryGeorgist** [comment]
@trietmnj i think you can address this request now.

**Comment by trietmnj** [comment]
I was able to add the vtl endpoints but only after removing citysdk. Not sure why, but it the vtl points weren't displayed while the package was installed. The current tmnt branch has the vtl working with the download layer, but citysdk is removed.

**Comment by HenryGeorgist** [comment]
I pulled tmnt and was able to see the vtl layers, great work. They are pretty cool huh. Create a PR and add me as a reviewer and i will review.
