### ISSUE TITLE
where is MapLoadingIndicator defined?

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#21]
Is it possible you forgot to add the maploading indicator plugin? i cannot find it in @corpsmap/corpsmap, i am getting a "cannot find pluginName of undefined" currently and no map is loading.

**Comment by trietmnj** [comment]
Try npm update, I updated corpsmap from v0.1.0 to v0.9.3 - the same as the nsi-survey-tool. Should be in the gigantic node_modules/@corpsmap/corpsmap/lib/dev.js. It's also in the prod.js file.

![image](https://user-images.githubusercontent.com/53122983/128644269-cf3a7509-e0bf-4a08-b56f-e3c0b83dd3bb.png)

**Comment by HenryGeorgist** [comment]
Great, I saw you bumped versions. My bad for forgetting to npm update! I will test it tonight.

**Comment by HenryGeorgist** [comment]
i was able to get the latest via npm. closing
