### ISSUE TITLE
add link to help files

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#3]

**Comment by HenryGeorgist** [comment]
please add a help button to the banner:
https://github.com/HydrologicEngineeringCenter/nsi-ui/blob/master/src/containers/main/banner.js
on the right side and have it navigate in a new tab to:
https://www.hec.usace.army.mil/fwlink/?linkid=nsi-download-tool

**Comment by trietmnj** [comment]
alright, I'm on it

**Comment by HenryGeorgist** [comment]
Closing
