### ISSUE TITLE
NSI download tool error

### ISSUE THREAD

**Issue by aestov** [HydrologicEngineeringCenter/nsi-ui#36]
Trying to access the NSI download tool via the link results in a 403 Error Page.  Happens on Chrome and Edge.

**Comment by HenryGeorgist** [comment]
Thanks for the report!
Please ensure you are logged into the vpn since thie NSI download page is currently behind the USACE firewall.

**Comment by HenryGeorgist** [comment]
@rbinmo1 sorry if I did not follow up. The NSI 2.0 data from 2019 is not publicly available. We hope to release an NSI datalayer in 2022 that is available to the public. Stay tuned.

**Comment by HenryGeorgist** [comment]
fixed with public release
