### ISSUE TITLE
Error in Download NSI data!

### ISSUE THREAD

**Issue by rbinmo1** [HydrologicEngineeringCenter/nsi-ui#37]
How could I download the NSI 2.0 data? Is NSI 2.0 data is publicly available?

I got this error message. Could you please explain in detail, how to download NSI data?

![image](https://user-images.githubusercontent.com/63298255/138723429-673fecd4-1c59-4d10-b77d-cf1c87db1893.png)

**Comment by HenryGeorgist** [comment]
fixed with public release
