### ISSUE TITLE
add login page

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#4]

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/nsi-survey-tool/tree/master/src/containers/login

see the login info here.

**Comment by trietmnj** [comment]
Is authentication supposed to lock out "/main" access in the nsi-survey-tool? As far as I can tell, "/" does go through the authentication with the auth api `https://ml-dev.sec.usace.army.mil/auth/v3/token` but the whole thing can be bypass by going directly to "/main".

**Comment by HenryGeorgist** [comment]
Yeah, routes will have to be reworked. Login page should be the first page, and map should not be accessible unless an authenitated user is authorized

**Comment by HenryGeorgist** [comment]
ugg - @trietmnj I should have linked you to the rgoss branch. my mistake.

https://github.com/HydrologicEngineeringCenter/nsi-survey-tool/tree/rgoss/src/containers/login

and see how routes are set up here.
https://github.com/HydrologicEngineeringCenter/nsi-survey-tool/blob/rgoss/src/app-bundles/routes-bundle.js

**Comment by HenryGeorgist** [comment]
@trietmnj looks great.
