### ISSUE TITLE
where to find public version of the NSI

### ISSUE THREAD

**Issue by rachelhamburger** [HydrologicEngineeringCenter/nsi-ui#44]
The documentation for the NSI 2022 states that "The public version of the NSI is releasable to the general public as it removes fields that are derived from licensed data", however, does not say where to find this public version of the dataset. Can someone point me in the right direction?

Thanks!

**Comment by HenryGeorgist** [comment]
NSI 2022 is in the process of being publicly released. It is not yet posted to a public url, but as soon as it does we will try to follow up with you. Keep checking in if you do not hear back from us in a few days.

**Comment by helenamlin** [comment]
Hi, I'm also looking to use the NSI 2022 data. Has it been publicly released yet? Thanks.

**Comment by trietmnj** [comment]
Hi, I apologize for the delay. The data is available to download now. You can replace {statefips} in the link below with the fips number of the state you are trying to download.

https://nsi.sec.usace.army.mil/downloads/nsi_2022/nsi_2022_{statefips}.gpkg.zip

For reference, here is a list of states and their corresponding fips number. The data to the major 50 states and the District of Columbia should be available now.

https://www.mercercountypa.gov/dps/state_fips_code_listing.htm

As an example, the download link to Maryland should be:

https://nsi.sec.usace.army.mil/downloads/nsi_2022/nsi_2022_24.gpkg.zip

A web-map tool is also available to make downloading more intuitive, but it is not yet available at a public url. I'm expecting the issue to be resolved relatively soon.

Please feel free to let us know if you run into any difficulty downloading the data.

**Comment by trietmnj** [comment]
Update: the web-map tool is now available.

https://nsi.sec.usace.army.mil/downloads/

**Comment by HenryGeorgist** [comment]
closing
