### ISSUE TITLE
Not able to access National Structure Inventory Dataset 

### ISSUE THREAD

**Issue by Samoht1989** [HydrologicEngineeringCenter/nsi-ui#47]
Clicking on the NSI tool does not open the download tool. It gives an error message saying server cannot be reached. Is there any way around to download the data?

**Comment by HenryGeorgist** [comment]
during disaster operations for Ian we found a problem with the geopackage assets for NSI 2022, we are fixing the error and anticipate a reupload by COB today.

Is your need urgent?

**Comment by Samoht1989** [comment]
Not urgent. I will check back next week if I can access it. Currently Im getting the following error while accessing the data. 

![image](https://user-images.githubusercontent.com/114755781/193294927-d76daa4b-a7e1-493a-b1c0-e83ff856f9f7.png)

**Comment by HenryGeorgist** [comment]
what link are you using? where did you find the link?

**Comment by Samoht1989** [comment]
It is the hyperlink "NIS download tool" in this page: https://www.hec.usace.army.mil/confluence/nsi/userguides/download-tool

**Comment by HenryGeorgist** [comment]
Noted. That link has just been updated. You should be able to access the site without a 403 error, but you will get an html index response on download while we are repairing the geopackages.  Stay tuned. Thanks for reporting the broken link.

**Comment by Samoht1989** [comment]
Thanks. I can access it now.

**Comment by HenryGeorgist** [comment]
service has been restored with links to download data now working.
