### ISSUE TITLE
update readme with a basic picture of the ui

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#7]

**Comment by trietmnj** [comment]
https://github.com/trietmnj/nsi-ui/blob/master/README.md

**Comment by HenryGeorgist** [comment]
@trietmnj feel free to stage a pull request, but i think that UI is a bit behind master now. I have added the state boundaries from the census.
Also, feel free to create a branch directly on this repo if you want, i will add you to the org
